name: emotion_sense
description: On-device face emotion, age, and gender recognition (100% offline).
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.12.0+1
  tflite_flutter: ^0.12.1
  google_mlkit_face_detection: ^0.13.1

  provider: ^6.0.0

  flutter_animate: ^4.5.0
  google_fonts: ^8.0.2
  audioplayers: ^6.6.0
  photo_manager: ^3.2.1
  flutter_slidable: ^4.0.3
  http: ^1.2.0

  shared_preferences: ^2.2.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.5

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/icons/app_icon.png
    background_color: "#0D0D1A"
    theme_color: "#4D7CFE"
  windows:
    generate: true
    image_path: assets/icons/app_icon.png
  macos:
    generate: true
    image_path: assets/icons/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/models/face_detection_short_range.tflite
    - assets/models/model_lite_age_q.tflite
    - assets/models/model_lite_gender_q.tflite
    - assets/models/age_gender_ethnicity_new.tflite
    - assets/sounds/
