org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
systemProp.http.socketTimeout=120000
systemProp.http.connectionTimeout=120000
systemProp.https.socketTimeout=120000
systemProp.https.connectionTimeout=120000
android.useAndroidX=true
android.enableJetifier=true
